<?php

/**
 * BelVG LLC.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 *
 ********************************************************************
 * @category   Belvg
 * @package    BelVG_FacebookFree
 * @author Pavel Novitsky <pavel@belvg.com>
 * @copyright  Copyright (c) 2010 - 2015 BelVG LLC. (http://www.belvg.com)
 * @license    http://store.belvg.com/BelVG-LICENSE-COMMUNITY.txt
 */

/* @var $this \BelVG\FacebookFree\Block\Init */

// @codingStandardsIgnoreFile
?>
<div id="fb-root"></div>
<script type="text/javascript">
    window.fbAsyncInit = function() {
        FB.init({
            appId      : '<?php echo $this->getAppId() ?>', // App ID
            status     : true, // check login status
            cookie     : true, // enable cookies to allow the server to access the session
            xfbml      : true  // parse XFBML
        });
    };

    // Load the SDK Asynchronously
    (function(d){
        var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement('script'); js.id = id; js.async = true;
        js.src = "//connect.facebook.net/<?php echo $this->getLocale() ?>/all.js";
        ref.parentNode.insertBefore(js, ref);
    }(document));

    function greet(id){
        FB.api('/me', function(response) {
            var src = 'https://graph.facebook.com/'+id+'/picture';
            $$('.welcome-msg')[0].insert('<img height="20" src="'+src+'"/>');
        });
    }

    function fblogin(){
        try {
            FB.login(function(response) {
                if (response.status == 'connected') {
                    window.location.href = '<?php echo $this->getLoginUrl() ?>';
                } else if (response.status === 'not_authorized') {
                    alert('Please, approve our application');
                } else {
                    // user is not logged in
                    window.location.reload();
                }
            }, {scope:'email'});
        } catch (err) {
            fblogin();
        }
        return false;
    }
</script>